import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providerQuery";
const inter = Inter({ subsets: ["latin"] });
import NextAuthProvider from "./providerSession";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <NextAuthProvider>
        <body className={`${inter.className} bg-dark w-screen h-screen text-white overflow-x-hidden`}>
          <Providers>
            {children}
          </Providers>
        </body>
      </NextAuthProvider>
    </html>
  );
}
